title: <p align="center"> Mrinmoy Thokdar </p>
logo: /assets/img/Self_Image.jpg
description:
  <p align="center">
  <a href="www.linkedin.com/in/mrinmoy-thokdar-7625b3b3/">LinkedIn</a> |
  <a href="https://github.com/Mrinmoy4CS">GitHub</a>
  <br>   
  I'm currently working on various Data Science & Machine learning related problems to relate
  my extensive domain knowledge with analytics to help create and add value to the my work.
  <br>
  </p>

  theme: jekyll-theme-minimal
